# Generated by Django 3.2.4 on 2021-08-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.course')),
                ('lec_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.lecture')),
                ('ref_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.reference')),
            ],
        ),
    ]
