# Generated by Django 3.2.4 on 2021-06-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='lec_id',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='lec_id',
        ),
        migrations.AddField(
            model_name='courses',
            name='s_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.subject'),
        ),
        migrations.AddField(
            model_name='reference',
            name='s_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.subject'),
        ),
    ]
