# Generated by Django 3.2.4 on 2021-06-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20210610_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lec', to='education.subject'),
        ),
    ]
