# Generated by Django 3.2.4 on 2021-08-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.lecture')),
            ],
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
