# Generated by Django 3.2.4 on 2021-06-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_lecture_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='s_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cor', to='education.subject'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='s_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='education.subject'),
        ),
    ]
