# Generated by Django 3.2.4 on 2021-08-07 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('education', '0005_favourite_course_favourite_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(choices=[('a', 'Hola'), ('b', 'Hello'), ('c', 'Bonjour'), ('d', 'Boas')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='typee',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourite_course',
            name='account_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='favourite_lecture',
            name='account_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
