# Generated by Django 3.2.4 on 2021-08-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20210807_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='my_field',
            field=models.CharField(choices=[('a', 'Hola'), ('b', 'Hello'), ('c', 'Bonjour'), ('d', 'Boas')], default='global', max_length=1),
        ),
    ]
