# Generated by Django 3.2.4 on 2021-08-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_auto_20210809_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='typee',
            field=models.CharField(choices=[(1, 'academic'), (2, 'functional')], default='academic', max_length=200),
        ),
    ]
