# Generated by Django 3.2.4 on 2021-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_lecture_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='typee',
            field=models.CharField(choices=[('a', 'global'), ('b', 'python'), ('c', 'java'), ('d', 'css'), ('e', 'c++'), ('f', 'c#'), ('g', 'html')], default='global', max_length=200),
        ),
    ]
