# Generated by Django 3.2.4 on 2021-08-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_course_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='typee',
            field=models.CharField(choices=[('1', 'academic'), ('2', 'functional')], default='1', max_length=200),
        ),
    ]
