# Generated by Django 3.2.4 on 2021-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_lecture_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='typee',
            field=models.CharField(choices=[('1', 'global'), ('2', 'python'), ('3', 'java'), ('4', 'css'), ('5', 'c++'), ('6', 'c#'), ('7', 'html')], default='1', max_length=200),
        ),
    ]
