# Generated by Django 3.2.4 on 2021-08-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_alter_course_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='typee',
            field=models.CharField(choices=[('academic', 'academic'), ('functional', 'functional')], default='academic', max_length=200),
        ),
    ]
