# Generated by Django 3.2.4 on 2021-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_alter_lecture_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='typee',
            field=models.CharField(choices=[('global', 'global'), ('python', 'python'), ('java', 'java'), ('css', 'css'), ('c++', 'c++'), ('c#', 'c#'), ('html', 'html')], default='global', max_length=200),
        ),
    ]
